import { readFileSync } from "node:fs";
const html=readFileSync("web/index.html","utf8");
const js=readFileSync("web/src/game-hardreset.js","utf8");
const home=readFileSync("web/src/home.js","utf8");
const css=readFileSync("web/style.css","utf8");
const checks=[["home screen",html.includes('id="homeScreen"')],["match screen",html.includes('id="matchScreen"')],["left movement stick",html.includes('id="stick"')],["no visible action grid",!html.includes('id="actions"')&&!html.includes('data-action=')],["home controller",html.includes('src/home.js')],["game controller",html.includes('game-hardreset.js')],["player database import",js.includes('player-pool.generated.js')],["gacha flow",home.includes('data-draw')],["match timer",js.includes('MATCH_DURATION = 90 * 60')&&js.includes('HALF_TIME_AT = 45 * 60')&&js.includes('MATCH_TIME_SCALE = 60')],["goal event",js.includes('football:goal')],["fulltime event",js.includes('football:fulltime')],["single AI loop",!js.includes('function aiStep')&&(js.match(/function teamAI\s*\(/g)||[]).length===1],["pass re-acquisition guard",js.includes('lastKickerUntil')],["touch flick input",js.includes('function rightMove')&&js.includes('function leftDown')&&js.includes('state.matchUp')&&js.includes('STUNNING SHOT')&&html.includes('TOUCH & FLICK')&&css.includes('#actionPad{display:none!important')],["touch flick pressure",js.includes('function callTeamPressure')&&js.includes('state.pressUntil')],["touch flick attack",js.includes('function triggerSharpTouch')&&js.includes('function activateShield')&&js.includes('function quickStopFaceGoal')&&js.includes('rightTapAt')],["touch flick defense mapping",js.includes('state.matchUp')&&js.includes('tackleControlled()')&&js.includes('function callTeamPressure')],["tackle action",js.includes('function tackleControlled')&&html.includes('id="tackleBtn"')],["goalkeeper save",js.includes('function goalkeeperAI')&&js.includes('setAction(gk,"save"')],
["player gameplay attributes",js.includes('function gameplayAttributes')&&js.includes('acceleration:7.5+gameplay.acceleration')&&js.includes('shooting:gameplay.shooting')&&js.includes('passing:gameplay.passing')&&js.includes('staminaRating:gameplay.stamina')],
["attribute-driven simulation",js.includes('const skill=mode==="shoot"')&&js.includes('userData.defending')&&js.includes('gkReflexes')&&js.includes('currentSpeed')]];
for(const [n,ok] of checks)if(!ok)throw new Error("Smoke check failed: "+n);
console.log("Web smoke checks passed:",checks.map(x=>x[0]).join(", "));