import { readFileSync } from "node:fs";
const html=readFileSync("web/index.html","utf8");
const js=readFileSync("web/src/game-hardreset.js","utf8");
const home=readFileSync("web/src/home.js","utf8");
const css=readFileSync("web/style.css","utf8");
const checks=[["home screen",html.includes('id="homeScreen"')],["match screen",html.includes('id="matchScreen"')],["left movement stick",html.includes('id="stick"')],["no visible action grid",!html.includes('id="actions"')&&!html.includes('data-action=')],["home controller",html.includes('src/home.js')],["game controller",html.includes('game-hardreset.js')],["player database import",js.includes('player-pool.generated.js')],["gacha flow",home.includes('data-draw')],["match timer",js.includes('MATCH_DURATION = 90 * 60')&&js.includes('HALF_TIME_AT = 45 * 60')&&js.includes('MATCH_TIME_SCALE = 60')],["goal event",js.includes('football:goal')],["fulltime event",js.includes('football:fulltime')],["single AI loop",!js.includes('function aiStep')&&(js.match(/function teamAI\s*\(/g)||[]).length===1],["pass re-acquisition guard",js.includes('lastKickerUntil')],["touch flick input",js.includes('function rightMove')&&js.includes('function leftDown')&&js.includes('state.matchUp')&&js.includes('STUNNING SHOT')&&html.includes('TOUCH & FLICK')&&css.includes('#actionPad{display:none!important')],["touch flick pressure",js.includes('function callTeamPressure')&&js.includes('state.pressUntil')],["touch flick attack",js.includes('function triggerSharpTouch')&&js.includes('function activateShield')&&js.includes('function quickStopFaceGoal')&&js.includes('rightTapAt')],["touch flick defense mapping",js.includes('state.matchUp')&&js.includes('tackleControlled()')&&js.includes('function callTeamPressure')&&js.includes('state.defenseRightTapAt')&&js.includes('RIGHT ×2<i>SWITCH</i>')],["tackle action",js.includes('function tackleControlled')&&html.includes('id="tackleBtn"')],["goalkeeper save",js.includes('function goalkeeperAI')&&js.includes('setAction(gk,"save"')],
["player gameplay attributes",js.includes('function gameplayAttributes')&&js.includes('acceleration:7.5+gameplay.acceleration')&&js.includes('shooting:gameplay.shooting')&&js.includes('passing:gameplay.passing')&&js.includes('staminaRating:gameplay.stamina')],
["attribute-driven simulation",js.includes('const skill=mode==="shoot"')&&js.includes('userData.defending')&&js.includes('gkReflexes')&&js.includes('currentSpeed')],
["defensive pressure simulation",js.includes('lastDefensiveContactAt')&&js.includes('"PRESSURE WIN"')&&js.includes('contactCooldown')],
["AI kick skill scaling",js.includes('function kick(player')&&js.includes('skillFactor=0.84+clamp(skill,45,99)')],
["player identity variation",js.includes('function improvePlayerIdentity')&&js.includes('improvePlayerIdentity(g);')&&js.includes('p.userData.identity')],
["player body proportions",js.includes('CapsuleGeometry(rad,len,5,8)')&&js.includes('-(len*.5+rad)')&&js.includes('new THREE.CylinderGeometry(0.34*shoulder,0.285*frame,0.70,12)')&&js.includes('sockColor=0xf1f3f5')&&js.includes('leftCalf=limb(leftThigh,0,-thighTotal,mat(sockColor')&&js.includes('g.scale.set(frame*rootScale,stature*rootScale,frame*rootScale)')&&js.includes('p.position.y=0.01;')],
["presentation polish",js.includes('new THREE.CanvasTexture(c)')&&js.includes('netMat=new THREE.MeshBasicMaterial')&&js.includes('function updateBroadcastCamera(dt)')&&js.includes('const midX=lerp(px,bx,.34)')&&html.includes('id="gestureGuide"')&&css.includes("#gestureGuide")],
["role body variation",js.includes('const roleHeight=role==="GK"?1.08')&&js.includes('const roleFrame=role==="DF"?1.045')&&js.includes('sockAccent=mat(shirtColor,.62)')],
["movement polish",js.includes('function resolvePlayerSeparation()')&&js.includes('const wa=aMov&&bMov ? .5 : (aMov||bMov ? 1 : 0);')&&js.includes('const response=clamp((p.userData.acceleration||7)*dt,0,1)')],
["sharp touch physics",js.includes('sharpTouchUntil:0')&&js.includes('const impulse=4.8*remain*remain')&&!js.includes('p.position.x=clamp(p.position.x+nx*2.7')],
["match squad integration",js.includes('function readMatchSquad()')&&js.includes('function syncMatchSquad()')&&html.includes('data-squad-ids')&&home.includes('football_match_squad')],
["economy persistence",home.includes('coins:Math.max(0,+localStorage.getItem("football_coins")||100)')&&home.includes('state.coins=Math.max(0,Math.floor(Number(state.coins)||0))')&&!home.includes('state.coins=999999999')],
["fluid formation gameplay",js.includes('fluidFormation=localStorage.getItem("football_fluid_formation")!=="0"')&&js.includes('if(fluidFormation){')&&home.includes('data-fluid-toggle')],
["full roster build path",readFileSync("scripts/build-player-pool.mjs","utf8").includes('console.log("Generated "+data.length+" players")')&&readFileSync("vercel.json","utf8").includes('"buildCommand": "node scripts/build-player-pool.mjs"')]];
for(const [n,ok] of checks)if(!ok)throw new Error("Smoke check failed: "+n);
console.log("Web smoke checks passed:",checks.map(x=>x[0]).join(", "));