import { readFileSync } from "node:fs";
const html=readFileSync("web/index.html","utf8");
const js=readFileSync("web/src/game-hardreset.js","utf8");
const home=readFileSync("web/src/home.js","utf8");
const css=readFileSync("web/style.css","utf8");
const checks=[["home screen",html.includes('id="homeScreen"')],["match screen",html.includes('id="matchScreen"')],["left movement stick",html.includes('id="stick"')],["no visible action grid",!html.includes('id="actions"')&&!html.includes('data-action=')],["home controller",html.includes('src/home.js')],["game controller",html.includes('game-hardreset.js')],["player database import",js.includes('player-pool.generated.js')],["gacha flow",home.includes('data-draw')],["match timer",js.includes('MATCH_DURATION = 90 * 60')&&js.includes('HALF_TIME_AT = 45 * 60')&&js.includes('MATCH_TIME_SCALE = 60')&&js.includes('state.matchState="prematch"')&&js.includes('football:kickoff')&&html.includes('id="kickoffBtn"')&&js.includes('function togglePause')&&js.includes('matchState==="goal"')],["goal event",js.includes('football:goal')],["fulltime event",js.includes('football:fulltime')],["single AI loop",!js.includes('function aiStep')&&(js.match(/function teamAI\s*\(/g)||[]).length===1],["pass re-acquisition guard",js.includes('lastKickerUntil')],["touch flick input",js.includes('function rightMove')&&js.includes('function leftDown')&&js.includes('state.matchUp')&&js.includes('function bindActionButton')&&js.includes('rightTapTimer')&&html.includes('TOUCH & FLICK')&&css.includes('#actionPad{')&&html.includes('id="shootBtn"')],["touch flick pressure",js.includes('function callTeamPressure')&&js.includes('state.pressUntil')],["touch flick attack",js.includes('function triggerSharpTouch')&&js.includes('function activateShield')&&js.includes('function quickStopFaceGoal')&&js.includes('rightTapAt')&&js.includes('function screenVector')&&js.includes('const aim=screenVector')],["touch flick defense mapping",js.includes('state.matchUp')&&js.includes('tackleControlled()')&&js.includes('function callTeamPressure')&&js.includes('state.defenseRightTapAt')&&js.includes('function switchPlayer')&&html.includes('id="switchBtn"')&&js.includes('mount.setPointerCapture')],["tackle action",js.includes('function tackleControlled')&&html.includes('id="tackleBtn"')],["goalkeeper save",js.includes('function goalkeeperAI')&&js.includes('setAction(gk,"save"')],
["player gameplay attributes",js.includes('function gameplayAttributes')&&js.includes('acceleration:7.5+gameplay.acceleration')&&js.includes('shooting:gameplay.shooting')&&js.includes('passing:gameplay.passing')&&js.includes('staminaRating:gameplay.stamina')],
["attribute-driven simulation",js.includes('const skill=mode==="shoot"')&&js.includes('userData.defending')&&js.includes('gkReflexes')&&js.includes('currentSpeed')],
["defensive pressure simulation",js.includes('lastDefensiveContactAt')&&js.includes('"PRESSURE WIN"')&&js.includes('contactCooldown')],
["AI kick skill scaling",js.includes('function kick(player')&&js.includes('skillFactor=0.84+clamp(skill,45,99)')],["AI tactical marking",js.includes('Goal-side marking')&&js.includes('markWeight')&&js.includes('space=home.filter')],
["player identity variation",js.includes('function improvePlayerIdentity')&&js.includes('improvePlayerIdentity(g);')&&js.includes('p.userData.identity')],
["player material declaration order",(()=>{
  const start=js.indexOf("function makePlayer(");
  const end=js.indexOf("\nconst FORMATION",start);
  if(start<0||end<0)return false;
  const body=js.slice(start,end);
  const decl=body.indexOf("const shirtMat=kitMat(team,.58)");
  const use=body.indexOf("const torso=part(",decl);
  return decl>0&&use>decl;
})()],
["player body proportions",js.includes('function makePlayer')&&js.includes('CapsuleGeometry(rad,len,5,8)')&&js.includes('-(len*.5+rad)')&&js.includes('sockColor=0xf1f3f5')&&js.includes('leftCalf=limb(leftThigh,0,-thighTotal,mat(sockColor')&&js.includes('g.scale.set(frame*rootScale,stature*rootScale,frame*rootScale)')&&js.includes('p.position.y=0.01;')],
["mobile pause control",js.includes('pauseBtn?.addEventListener("click"')&&js.includes("togglePause()")&&css.includes("#topTools .pauseBtn{pointer-events:auto}")],["pointer cancel safety",js.includes("function leftCancel(e)")&&js.includes("function rightCancel(e)")&&js.includes("clearActionCharge(type,e,\"action-pointercancel\")")&&js.includes('pointercancel",leftCancel')&&js.includes('pointercancel",(e)=>{if(e.pointerId===state.leftPointerId)leftCancel(e);else rightCancel(e);')],["asset cache bust",html.includes("style.css?v=20261004-premium-05")&&html.includes("game-hardreset.js?v=20261004-match-controls-06")],
["mobile input recovery",js.includes('function resetActiveInput(reason="cancel")')&&js.includes('document.addEventListener("visibilitychange"')&&js.includes('orientationchange')&&js.includes("state.rightGesture=null")],
["presentation polish",js.includes('new THREE.CanvasTexture(c)')&&js.includes('netMat=new THREE.MeshBasicMaterial')&&js.includes('function updateBroadcastCamera(dt)')&&js.includes('scene.fog = new THREE.FogExp2')&&js.includes('renderer.shadowMap.enabled = true')&&html.includes('id="gestureGuide"')&&html.includes('id="matchPause"')&&html.includes('id="pauseBtn"')&&css.includes("#gestureGuide")],
["role body variation",js.includes('const roleHeight=role==="GK"?1.08')&&js.includes('const roleFrame=role==="DF"?1.045')&&js.includes('sockAccent=mat(shirtColor,.62)')],
["movement polish",js.includes('function resolvePlayerSeparation()')&&js.includes('const wa=aMov&&bMov ? .5 : (aMov||bMov ? 1 : 0);')&&js.includes('const response=clamp((p.userData.acceleration||7)*dt,0,1)')&&js.includes('const dash=defending?state.dashHeld:(state.rightHeld||state.dashHeld)')&&js.includes('const jockey=defending&&state.matchUp&&!dash')&&js.includes('const angleDamp')],
["sharp touch physics",js.includes('sharpTouchUntil:0')&&js.includes('const impulse=4.8*remain*remain')&&js.includes('const dir=screenVector')&&!js.includes('p.position.x=clamp(p.position.x+nx*2.7')],["first touch receiving",js.includes('possessionState==="RECEIVING"')&&js.includes('receivingUntil')&&js.includes('receivingVelocity')&&js.includes('touchFactor')&&js.includes('incomingSpeed>3.8')],
["charged action controls",js.includes('function beginActionCharge')&&js.includes('function finishActionCharge')&&js.includes('powerGauge')&&html.includes('id="powerGauge"')],
["match squad integration",js.includes('function readMatchSquad()')&&js.includes('function syncMatchSquad()')&&home.includes('data-squad-ids')&&home.includes('football_match_squad')],
["economy persistence",home.includes('const storedCoins=+localStorage.getItem("football_coins")')&&home.includes('storedCoins===999999999?100')&&home.includes('state.coins=Math.max(0,Math.floor(Number(state.coins)||0))')&&!home.includes('state.coins=999999999')],
["fluid formation gameplay",js.includes('fluidFormation=localStorage.getItem("football_fluid_formation")!=="0"')&&js.includes('if(fluidFormation){')&&home.includes('data-fluid-toggle')],["team playstyle gameplay",js.includes('teamPlaystyle=localStorage.getItem("football_team_playstyle")||"POSSESSION"')&&js.includes('advanceBase=teamPlaystyle')&&js.includes('mfPush=teamPlaystyle')&&home.includes('data-playstyle')],
["full roster build path",readFileSync("scripts/build-player-pool.mjs","utf8").includes('console.log("Generated "+data.length+" players")')&&readFileSync("vercel.json","utf8").includes('"buildCommand": "node scripts/build-player-pool.mjs"')],["finite special contract box",home.includes('SPECIAL_BOX_KEY')&&home.includes('specialBoxSeed()')&&home.includes('specialBoxCards()')&&home.includes('consumeSpecialBox')&&home.includes('kind==="special"?specialBoxCards()')&&home.includes('n===10')],
["contract headliners",home.includes('HEADLINER_SPECS')&&home.includes('3 FEATURED PLAYERS')&&home.includes('HEADLINER GUARANTEED')&&home.includes('activeSpecialHeadliners')&&home.includes('n===10')],
["contract selection flow",home.includes('function signSelectedPlayer')&&home.includes('activeBanner==="nominating"||activeBanner==="selection"')],
["contract premium reveal",home.includes('function stagePlayerCard')&&home.includes('function signingPackMarkup')&&html.includes('id="stageCard"')&&css.includes('.stagePlayerCard')],["mobile control presentation",css.includes('#actionPad.attacking .shoot')&&css.includes('#actionPad.defending .switch')&&css.includes('#powerGauge')&&css.includes('.matchAction[data-pressed="1"]')&&html.includes('id="pauseBtn"')&&html.includes('id="resumeBtn"')],
["card id squad resolver",js.includes('const [baseId,variant]=id.split("-")')&&js.includes('cardType:variant.toUpperCase()')]];
for(const [n,ok] of checks)if(!ok)throw new Error("Smoke check failed: "+n);
console.log("Web smoke checks passed:",checks.map(x=>x[0]).join(", "));